version: '2'

services:
  helpy:
    build: .
    restart: always
    ports:
      - "80:8080"
    volumes:
      - .:/helpy
    env_file: docker/.env
    links:
      - postgres
      - mailcatcher
    depends_on:
      - postgres
      - mailcatcher
  postgres:
    image: postgres:9.4
    restart: always
    env_file: docker/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 127.0.0.1:1080:1080
    restart: always
